// Canonical origin for the marketing site. ONE source of truth: metadataBase,
// every per-page canonical, robots.ts, sitemap.ts and the JSON-LD all read it.
//
// It is deliberately the WWW host. The apex (prepwise-app.com) 301s here from the
// Cloudflare worker, with two exemptions that must never be canonicalised:
//   - /r/*          recipe-share Universal Links were minted on the apex
//   - /.well-known/* the AASA must resolve on the apex with no redirect
// The iOS app registers `applinks:prepwise-app.com` (apex only), which is what
// makes those two exemptions load-bearing rather than cosmetic.
export const SITE_URL = "https://www.prepwise-app.com";

// Every crawlable route in the static export. sitemap.ts enumerates this, so a
// new route is added here once rather than in a hand-kept sitemap.xml.
//
// `lastModified` is a real content date, NOT the build date. A sitemap that
// stamps "now" on every deploy teaches crawlers the field is meaningless, and
// Google discounts it. Bump the entry when the page's content actually changes;
// for the legal routes that is the "Last Updated" line the page itself renders.
//
// Blog POSTS are deliberately NOT listed here. They are enumerated by
// sitemap.ts from the content directory, so publishing a post cannot leave the
// sitemap stale by forgetting a line in two places at once. Everything that is
// not generated from content still belongs here.
export const SITE_ROUTES = [
  { path: "/", lastModified: "2026-07-26", changeFrequency: "weekly", priority: 1.0 },
  { path: "/faq", lastModified: "2026-07-26", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog", lastModified: "2026-08-11", changeFrequency: "weekly", priority: 0.7 },
  { path: "/privacy", lastModified: "2026-09-08", changeFrequency: "yearly", priority: 0.5 },
  { path: "/terms", lastModified: "2026-03-09", changeFrequency: "yearly", priority: 0.5 },
] as const;

// The sitewide title and description. Title 50-60 chars, meta description
// 150-160, both measured DECODED (an "&" is one character to Google, five in
// the HTML source). Enforced by landing/scripts/verify-seo.mjs; rationale in
// landing/seo/on-page-checklist.md.
//
// They live here rather than in layout.tsx because the sitewide JSON-LD graph
// (lib/schema.ts) needs the description too, and two copies of a string that
// must match is how the <meta> and the schema quietly drift apart.
export const SITE_TITLE = "PrepWise: AI Meal Planner & Pantry Tracker for iPhone";
export const SITE_DESCRIPTION =
  "Stop guessing what to cook. PrepWise plans your meals from the food already in your pantry, tracks macros, and writes the shopping list. Free on iPhone.";

// 1200x630 social card, generated by landing/scripts/make-brand-assets.py and
// committed to public/.
//
// It lives here rather than in layout.tsx because Next REPLACES the `openGraph`
// object wholesale when a page redefines it - it does not merge field by field.
// Every page that sets its own openGraph therefore has to restate the image.
// Not restating it is why /privacy and /terms shipped with no og:image at all
// until 2026-07-26. verify-seo.mjs now fails the build on a missing og:image;
// this export is what makes satisfying it a one-line import.
export const OG_IMAGE = {
  url: "/og-image.png",
  width: 1200,
  height: 630,
  alt: "PrepWise: meal planning that starts with what is in your pantry",
} as const;

// In-page anchors only work on the home page, so every nav link is written
// absolute-from-root ("/#features"). A bare "#features" on /faq scrolls
// nowhere and looks broken.
export const NAV_LINKS = [
  { label: "Features", href: "/#features" },
  { label: "How It Works", href: "/#how-it-works" },
  { label: "Blog", href: "/blog" },
  { label: "FAQ", href: "/faq" },
] as const;

// The footer's internal-linking block. Every crawlable page reachable from
// every page: the baseline internal link graph the SEO checklist asks for.
export const FOOTER_LINKS = [
  {
    heading: "Product",
    links: [
      { label: "Features", href: "/#features" },
      { label: "How it works", href: "/#how-it-works" },
      { label: "Download for iPhone", href: "/#cta" },
    ],
  },
  {
    heading: "Learn",
    links: [
      { label: "Blog", href: "/blog" },
      { label: "FAQ", href: "/faq" },
    ],
  },
  {
    heading: "Company",
    links: [
      { label: "Privacy Policy", href: "/privacy" },
      { label: "Terms of Use", href: "/terms" },
    ],
  },
] as const;

// App Store download link.
// `pt` = provider token, `ct` = campaign token (App Store Connect attribution),
// `mt=8` = App Store medium. The `ct` value is the DEFAULT campaign token; it is
// overridden at click time with the incoming ad's utm_content/utm_campaign so
// App Store Connect attributes installs back to the specific ad. See lib/analytics.ts.
export const APP_STORE_URL =
  process.env.NEXT_PUBLIC_APP_STORE_URL ||
  "https://apps.apple.com/app/apple-store/id6754949361?pt=128248695&ct=Landing%20Page%20Download%20Button&mt=8";

// Analytics IDs (set in .env.local / Cloudflare Pages env vars).
// Tracking no-ops gracefully when these are empty, so the site works without them.
export const META_PIXEL_ID = process.env.NEXT_PUBLIC_META_PIXEL_ID || "";
export const GA_MEASUREMENT_ID = process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID || "";

export const LEGAL_LINKS = {
  privacy: "/privacy",
  terms: "/terms",
} as const;

// The footer renders its legal links from FOOTER_LINKS (so they sit in the
// sitemap-style block with everything else), which means the two lists could
// silently diverge and ship a footer pointing at a page that does not exist.
// FOOTER_LINKS stays a literal so its labels stay typed, so the pairing is
// asserted at module load instead. Under `output: "export"` this runs during
// the build and fails it, which is the point.
if (
  !FOOTER_LINKS.some((g) => g.links.some((l) => l.href === LEGAL_LINKS.privacy)) ||
  !FOOTER_LINKS.some((g) => g.links.some((l) => l.href === LEGAL_LINKS.terms))
) {
  throw new Error(
    "FOOTER_LINKS no longer contains both LEGAL_LINKS paths: the footer and the legal routes have drifted"
  );
}

export const SOCIAL_LINKS = {
  instagram: "https://www.instagram.com/prepwiseapp/",
  tiktok: "https://www.tiktok.com/@prepwiseapp",
  twitter: "https://x.com/PrepWiseApp",
} as const;

export const SUPPORT_EMAIL = "mailto:support@prepwise-app.com";

export const FEATURES = [
  {
    icon: "Sparkles" as const,
    title: "Recipes That Match Your Reality",
    description:
      "Every recipe shows a real-time availability indicator. Green means you have everything. You'll always know what you can cook tonight, not just what you wish you could.",
  },
  {
    icon: "Package" as const,
    title: "Your Kitchen, Perfectly Organized",
    description:
      "Track every ingredient. PrepWise reserves ingredients for planned meals so you never accidentally double-book your last chicken breast. When it's time to shop, your list is already written.",
  },
  {
    icon: "CalendarDays" as const,
    title: "AI That Actually Helps",
    description:
      'Ask PrepWise to "make a high-protein dinner with the chicken and sweet potatoes in my pantry" and it delivers. Custom recipes, full-week plans, and pantry suggestions, all voice-powered.',
  },
  {
    icon: "ShoppingCart" as const,
    title: "Macros Without the Math",
    description:
      "Every recipe automatically calculates calories, protein, carbs, and fat. Nutrition tracking is built into your meal planning process, not bolted on as an afterthought.",
  },
] as const;

export const STEPS = [
  {
    number: 1,
    title: "Track Your Pantry",
    description:
      "Snap a grocery receipt and your pantry updates automatically, or add ingredients manually in seconds.",
  },
  {
    number: 2,
    title: "Plan Your Meals",
    description:
      "Browse recipes filtered by what's in your kitchen right now, or ask the AI to build your full week in seconds.",
  },
  {
    number: 3,
    title: "Shop & Cook",
    description:
      "Your shopping list writes itself: only what you actually need, based on your meal plan and what's already in your pantry.",
  },
] as const;

export const SHOWCASE_SLIDES = [
  { src: "/promo/C1.png", caption: "Plan meals around what you actually have" },
  { src: "/promo/C2.png", caption: "AI-powered recipe creation" },
  { src: "/promo/C3.png", caption: "Smart shopping lists, zero guesswork" },
  { src: "/promo/C4.png", caption: "Every ingredient, always on hand" },
  { src: "/promo/C5.png", caption: "Your recipe collection, beautifully organized" },
  { src: "/promo/C6.png", caption: "Track macros, without the hassle" },
  { src: "/promo/C7.png", caption: "From fridge to plate, without a shop" },
  { src: "/promo/C9.png", caption: "Designed for night owls, full dark mode"},
  { src: "/promo/C10.png", caption: "Get started in 60 seconds" },
] as const;

export const STATS = [
  { value: "Real-Time", label: "Recipe Availability" },
  { value: "Automatic", label: "Macro Tracking" },
  { value: "Offline", label: "Works Anywhere" },
] as const;
